[package]
name = "gemicli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = '4', features = ['derive'] }
reqwest = { version = '0.11', features = ['blocking', 'json'] }
serde = { version = '1.0', features = ['derive'] }
colored = '2.0'
